# Generated by Django 4.2.12 on 2025-01-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "size",
            },
        ),
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
        migrations.RemoveField(
            model_name="category",
            name="image",
        ),
        migrations.RemoveField(
            model_name="product",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="product",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="subcategory",
            name="description",
        ),
        migrations.RemoveField(
            model_name="subcategory",
            name="image",
        ),
        migrations.RemoveField(
            model_name="subcategory",
            name="name",
        ),
        migrations.AddField(
            model_name="product",
            name="colour",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="final_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="product",
            name="is_in_stock",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="sub_name",
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="product_app.size"
            ),
        ),
    ]
