# Generated by Django 4.2.12 on 2025-01-16 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0005_favorite"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Favorite",
        ),
    ]
