# Generated by Django 4.2.12 on 2025-01-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0006_delete_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
