# Generated by Django 4.2.12 on 2025-01-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0007_product_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
