# Generated by Django 4.2.12 on 2025-01-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0007_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="reviews",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
