# Generated by Django 5.0.7 on 2025-01-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0008_alter_product_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'image_slider',
            },
        ),
    ]
