# Generated by Django 4.2.12 on 2025-01-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0011_remove_product_image_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="ProductImage",
        ),
    ]
