# Generated by Django 5.1.5 on 2025-01-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0013_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to="subcategories_icons"
            ),
        ),
    ]
