# Generated by Django 5.1.5 on 2025-02-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0015_color_remove_product_colour_product_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="average_rating",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="total_ratings",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
