# Generated by Django 5.1.5 on 2025-02-11 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0016_product_average_rating_product_total_ratings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="average_rating",
        ),
        migrations.RemoveField(
            model_name="product",
            name="total_ratings",
        ),
    ]
