# Generated by Django 5.1.5 on 2025-02-11 19:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0017_remove_product_average_rating_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productrating",
            unique_together={("product", "user")},
        ),
        migrations.RemoveField(
            model_name="productrating",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="productrating",
            name="session_id",
        ),
    ]
