# Generated by Django 4.2.12 on 2025-01-17 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0008_alter_product_created_at"),
        ("wishlist_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wishlist",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="product_app.product"
            ),
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="added_at",
        ),
    ]
