# Generated by Django 4.2.12 on 2025-01-17 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0008_alter_product_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wishlist_app", "0002_alter_wishlist_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlist",
                to="product_app.product",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wishlist",
            unique_together={("user", "product")},
        ),
    ]
