# Generated by Django 4.2.12 on 2025-01-17 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist_app", "0003_alter_wishlist_product_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wishlist",
            unique_together=set(),
        ),
    ]
