# Generated by Django 4.2.12 on 2025-01-16 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart_app", "0002_coupon_cart_total_price_cart_coupon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="total_price",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="created_at",
        ),
        migrations.AddField(
            model_name="coupon",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("shipping_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("coupon_code", models.CharField(blank=True, max_length=50, null=True)),
                ("first_name", models.CharField(max_length=100)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("street_address", models.CharField(max_length=255)),
                ("apartment", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=15)),
                ("email_address", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cart_app.cart"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
